### ISSUE TITLE
Ensure that keys work across platforms

### ISSUE THREAD

**Issue by gmaclennan** [noffle/safe-fs-blob-store#5]
Windows uses `\` by default as a path separator, whereas Linux and Mac use `/`. We use `path.sep()` in the code to use the correct separator, but I think that this may mean that keys are not consistent across platforms. Specifically, we want to be able to create a blob-store on one platform, and use the same keys on the other platform, and it should all just work. I'm concerned that the current implementation will fail if we move the store between platforms, we should test this.

Windows does understand the forward-slash (`/`) in path names but there are some weird exceptions around pathnames over 260 characters long and paths with unicode characters:

- https://docs.microsoft.com/en-us/windows/desktop/FileIO/naming-a-file#maximum-path-length-limitation
- https://superuser.com/questions/176388/why-does-windows-use-backslashes-for-paths-and-unix-forward-slashes#176395

We might want to use something like [upath](https://www.npmjs.com/package/upath) or [slash](https://github.com/sindresorhus/slash) but I'm unclear exactly where the issues might come up so we need to do some testing.

**Comment by hackergrrl** [comment]
done
